apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: click
    release: prometheus-stack
  name: click-app-servicemonitor
  namespace: python-monitoring
spec:
  endpoints:
    - interval: 2s
      port: click-app
      path: /metrics
  selector:
    matchLabels:
      app: click
  namespaceSelector:
    matchNames:
      - python-monitoring