apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: python-monitoring
  labels:
    release: prometheus-stack 
   
spec:
  route:
    receiver: slack-notifications
    groupWait: 5s
    groupInterval: 10s
    repeatInterval: 1m
  receivers:
    - name: slack-notifications
      slackConfigs:
        - apiURL:
            name: alertmanager-slack-config
            key: webhook_url
          channel: "#all-monitor"
          sendResolved: true
          title: '{{ .CommonAnnotations.summary }}'
          text: '{{ .CommonAnnotations.description }}'



