apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: python-monitoring
  labels:
    release: prometheus-stack 
   
spec:
  route:
    receiver: slack-notifications
    groupBy:
      - alertname
      - namespace
    groupWait: 5s
    groupInterval: 10s
    repeatInterval: 1m

  receivers:
    - name: slack-notifications
      slackConfigs:
        - channel: '#nzsaasops'
          apiURL:
            name: slack-secret
            key: webhook_url
          sendResolved: true
          text: |
            *Alert:* {{ .CommonLabels.alertname }}
            *Namespace:* {{ .CommonLabels.namespace }}
            *Severity:* {{ .CommonLabels.severity | default "error" }}
            *Summary:* {{ .CommonAnnotations.summary }}
            *Description:* {{ .CommonAnnotations.description }}
        
