# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: user-registration-app
  namespace: python-monitoring
  labels: 
    app: user-registration-app
spec:
  selector:
    app: user-registration-app
  type: ClusterIP
  ports:
  - name: user-reg
    port: 5000
    targetPort: 5000
---
