# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: user-registration-app
  namespace: python-monitoring
spec:
  selector:
    app: user-registration-app
  type: NodePort
  ports:
  - name: user-registration-app
    port: 5000
    targetPort: 5000
    nodePort: 30001
---
