apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alert-rules
  namespace: python-monitoring
  labels:
    release: prometheus-stack  # Must match your Prometheus CR
spec:
  groups:
  - name: user-reg.rules
    rules:
    - alert: HighRequestLatency
      expr: histogram_quantile(0.95, sum(rate(flask_request_latency_seconds_bucket{endpoint="/register"}[5m])) by (le)) > 0.8
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High request latency on user registration endpoint"
        description: "95th percent latency on / is more than 0.8 sec for straight 1m."

    - alert: TooManyPostRequests
      expr: increase(flask_app_request_count_total{endpoint="/register"}[2m]) > 5
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "Too many POST requests to /register"
        description: "More than 5 POST requests/sec to /register endpoint for 2 minutes."
        
    - alert: NoUserRegistration
      expr: increase(registered_users_total[10m]) == 0
      for: 10m
      labels:
        severity: critical
      annotations:
        summary: "No new users registered"
        description: "No user registrations have occurred in the past 10 minutes."
    - alert: Pods not running
      expr: kube_pod_status_phase{phase!="Running"} > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.pod }} not in healthy state in {{ $labels.namespace }}"
        description: "One or more pods are not in the Running state for more than 1 minutes."