{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "slack-secret",
    "namespace": "python-monitoring",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "slack-secret",
        "namespace": "python-monitoring",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "webhook_url": "AgAtIA7juqkmk4yTCQ9/BDNWL7s3s+tv4rL6VDT1pvXV5jRwsiPaRNbUrSMghPjwoP2vAYFv/kZzQnKoDm2FsOVVqtPZu2/IsuNxXFQ40U5UrGcOESoMhLji1ErOJ6zkbj2TtTBJXVrgLoDEka8GEYZozIvCweKQQU4/asfGgeh5jOHhaXuv7UZR0PUniYa4uNLplkKj4RxKnYEMxGkH3wKGaJCRIw+Q2RJTbK8JqQuparbTYRf8B/XSwggOR2Klkzs65CM1SW25gkcj5zJbBF8nXh/1HImdyPsjMcSmUfhYlU67WJQG6ZojiaX6nOeJ143UAjf0kW8dbyjGiAmZb7iANLU1J/RK5yrxpgG0ggFYMlxMwgEUQOetGZGyl/S20Dm3qQ56/owTkl30kpCCdxcfgSIjU8hEv4A3yjzayhFn8RmqlCxetcTAOgMW4X4nZIrJ396puO45FJvz5BLoRSfk4tRY/fAeAXnpze1Bt8BuYcuGsHel2CzxjgIob3mGGfpn2f6af7gKIMASQ6HPZVXgXK9fL1vCuX9EF9ie1C1x1JU41jorE5TQodHZ5tBZOxtaOcRoi6lBL0Hri7/qKvGyFDC/vuWU145apedeeuX8/RLQCl/QpXADV+ylcPx/RAp33z8NLtmesjXig3fZIPnqnh+4mOAPuQC3cQaGx6HhZhNIY+uC0G8q5+BvGHWCqbnLoMFoaY0R7Ze2Epmi+SRT2Uth3dpfefbSp/uOsD5lP+K3gpBlpFQIUXid+iJOegOBKhzBiAO1vjldznrUJXemhuUmzgqKyLJ5FqYuclj2H5U="
    }
  }
}