# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test and build


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # uses: actions/checkout@v4
      uses: actions/checkout@v2         
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask prometheus_client pytest
        pip install flake8
#   Testing the python code with flake8 and pytest

    - name: Run linting tests
      run: |
        flake8 --ignore=E501,E203,W503 .
    
